development:
  adapter: postgis
  postgis_extension: postgis
  host: localhost #10.1.0.73
  port: 5432
  #encoding: UTF8 #LATIN1
  #collate: en_US.UTF8
  #ctype: en_US.UTF8
  database: geobase
  pool: 5
  username: geo
  password: geo
  #schema_search_path: "public,postgis"
  #script_dir: /Library/PostgreSQL/9.2/share/postgresql/contrib/postgis #MAC OS
  #script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5

production:
  adapter: postgis
  postgis_extension: postgis
  host: localhost #10.1.0.73
  port: 5432
  #encoding: UTF8 #LATIN1   #utf8
  #collate: en_US.UTF8
  #ctype: en_US.UTF8
  database: geobase
  pool: 5
  username: geo
  password: geo
  #schema_search_path: "public,postgis"
  #script_dir: /Library/PostgreSQL/9.2/share/postgresql/contrib/postgis
  #script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5

# test:
#   adapter: postgis
#   encoding: UTF8
#   database: georails_test
#   pool: 5
#   username: geo
#   password: geo
#   schema_search_path: "public,postgis"
#   script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5